2024-04-11 10:00:00.484 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an unhandled Exception: 
System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-04-11 10:00:00.486 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024-04-11 10:32:15.170 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:32:15.170 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:33:25.551 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:33:25.551 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:37:32.359 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:37:32.359 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:39:31.142 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:39:31.142 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Framework.Rbac.Application.Services.FileService.Post(IFormFileCollection file) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Application\Services\FileService.cs:line 81
   at lambda_method1653(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:39:31.280 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:39:31.281 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:41:54.200 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:41:54.200 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Framework.Rbac.Application.Services.FileService.Post(IFormFileCollection file) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Application\Services\FileService.cs:line 81
   at lambda_method1653(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:41:54.328 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:41:54.328 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 10:44:13.866 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 10:44:13.866 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1488(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 11:04:26.073 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 11:04:26.074 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Framework.Rbac.Application.Services.FileService.Post(IFormFileCollection file) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Application\Services\FileService.cs:line 81
   at lambda_method1653(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 11:06:37.510 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 11:06:37.510 +08:00 [ERR] Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Guid[]'.
   at SqlSugar.IDataRecordExtensions.GetArray[T](IDataReader dr, Int32 i)
   at SqlSugarEntity(IDataRecord)
   at SqlSugar.IDataReaderEntityBuilder`1.Build(IDataRecord dataRecord)
   at SqlSugar.DbBindAccessory.GetEntityListAsync[T](SqlSugarProvider context, IDataReader dataReader)
   at SqlSugar.DbBindProvider.DataReaderToListAsync[T](Type type, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](Boolean isComplexModel, Type entityType, IDataReader dataReader)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.ToPageListAsync(Int32 pageIndex, Int32 pageSize, RefAsync`1 totalNumber)
   at Yi.Framework.Rbac.Application.Services.QuestionService.GetListAsync(QuestionGetListInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.GlobalFeatures.GlobalFeatureInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at lambda_method1611(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 11:52:08.490 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "POST api/app/file" for actions - Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application),Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Yi.Framework.Rbac.Domain.Authorization.RefreshTokenMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Domain\Authorization\RefreshTokenMiddleware.cs:line 47
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 11:52:17.415 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "POST api/app/file" for actions - Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application),Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Volo.Abp.AspNetCore.MultiTenancy.MultiTenancyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Yi.Framework.Rbac.Domain.Authorization.RefreshTokenMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Domain\Authorization\RefreshTokenMiddleware.cs:line 47
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 11:54:10.282 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application)
Yi.Framework.Rbac.Application.Services.FileService.Post (Yi.Framework.Rbac.Application)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 11:55:44.712 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Yi.Abp.Application.Services.FileService.Post (Yi.Abp.Application)
Yi.Framework.Rbac.Application.Services.FileService.Post (Yi.Framework.Rbac.Application)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 12:00:52.868 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 12:00:52.869 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 147
   at lambda_method1490(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 12:00:58.748 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 12:00:58.748 +08:00 [ERR] Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 169
   at lambda_method1490(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 12:01:19.381 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 12:01:19.381 +08:00 [ERR] Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 169
   at lambda_method1490(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 12:14:02.341 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Yi.Abp.Application.Services.FileService.Get (Yi.Abp.Application)
Yi.Framework.Rbac.Application.Services.FileService.Get (Yi.Framework.Rbac.Application)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 12:15:33.543 +08:00 [ERR] An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Yi.Abp.Application.Services.FileService.Get (Yi.Abp.Application)
Yi.Framework.Rbac.Application.Services.FileService.Get (Yi.Framework.Rbac.Application)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
2024-04-11 12:17:49.624 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 12:17:49.625 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Framework.Rbac.Application.Services.FileService.Post(IFormFileCollection file) in D:\vs_space\Yi\Yi.Abp.Net8\module\rbac\Yi.Framework.Rbac.Application\Services\FileService.cs:line 81
   at lambda_method1662(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 13:00:00.741 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an unhandled Exception: 
System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-04-11 13:00:00.743 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024-04-11 13:38:51.978 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 13:38:51.979 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 147
   at lambda_method1562(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 13:40:30.008 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 13:40:30.008 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 147
   at lambda_method1562(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 13:41:28.851 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 13:41:28.851 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 147
   at lambda_method1562(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 13:41:59.268 +08:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "对不起，在处理您的请求期间产生了一个服务器内部错误！！",
  "details": null,
  "data": {},
  "validationErrors": null
}

2024-04-11 13:41:59.268 +08:00 [ERR] 文件上传为空！
System.ArgumentException: 文件上传为空！
   at Yi.Abp.Application.Services.FileService.Post(IFormFileCollection file, Nullable`1 questionid) in D:\vs_space\Yi\Yi.Abp.Net8\src\Yi.Abp.Application\Services\FileService.cs:line 147
   at lambda_method1562(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-04-11 14:00:00.660 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an unhandled Exception: 
System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-04-11 14:00:00.662 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2024-04-11 16:00:00.890 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an unhandled Exception: 
System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2024-04-11 16:00:00.894 +08:00 [ERR] Job DEFAULT.InterestRecordsJob threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.AggregateException: One or more errors occurred. (BiyingBank获取数据异常)
 ---> System.Exception: BiyingBank获取数据异常
 ---> Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Integer. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 24
   --- End of inner exception stack trace ---
   at Yi.Framework.Bbs.Domain.Managers.BankValue.BiyingBankValueProvider.GetValueAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankValue\BiyingBankValueProvider.cs:line 29
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Yi.Framework.Bbs.Domain.Managers.BankManager.GetThirdPartyValue() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 68
   at Yi.Framework.Bbs.Domain.Managers.BankManager.CreateInterestRecordsAsync() in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Domain\Managers\BankManager.cs:line 82
   at Yi.Framework.Bbs.Application.Jobs.InterestRecordsJob.Execute(IJobExecutionContext context) in D:\vs_space\Yi\Yi.Abp.Net8\module\bbs\Yi.Framework.Bbs.Application\Jobs\InterestRecordsJob.cs:line 29
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
